fix image name
I got the error message:
Error: buildx call failed with: error: failed to solve: rpc
error: code = Unknown desc = server message:
insufficient_scope: authorization failed

In https://github.com/docker/build-push-action/issues/105 it was
suggested that ghcr.io prefix was missing